package blog.model;


public class Location {
	protected int locationId;
	protected String country;
	protected String province;
	protected String regin1;
	protected String regin2;
	protected String wineryName;
	
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public Location(int locationId, String country, String province, String regin1,
			String regin2, String wineryName) {
		this.locationId = locationId;
		this.country = country;
		this.province = province;
		this.regin1 = regin1;
		this.regin2 = regin2;
		this.wineryName = wineryName;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public Location(String wineryName) {
		this.wineryName = wineryName;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Location(String country, String province, String regin1,
			String regin2, String wineryName) {
		this.country = country;
		this.province = province;
		this.regin1 = regin1;
		this.regin2 = regin2;
		this.wineryName = wineryName;
	}

	public int getLocationId() {
		return locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getRegin1() {
		return regin1;
	}

	public void setRegin1(String regin1) {
		this.regin1 = regin1;
	}

	public String getRegin2() {
		return regin2;
	}

	public void setRegin2(String regin2) {
		this.regin2 = regin2;
	}

	public String getWineryName() {
		return wineryName;
	}

	public void setWineryName(String wineryName) {
		this.wineryName = wineryName;
	}

	
}